services:
  # PostgreSQL service (destination)
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # PgAdmin service to interact with PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # Airflow Webserver
  airflow:
    image: apache/airflow:2.7.2
    container_name: airflow_etl
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW_CORE_EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    env_file:
      - .env      # loading env_file to be used within airflow to run DAGs
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: ["webserver"]

  # Airflow Scheduler
  airflow_scheduler:
    image: apache/airflow:2.7.2
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
    command: ["scheduler"]

  # Python ETL Application Container (Dockerfile)
  etl_app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app  # Syncs local project directory with /app inside the container
    depends_on:
      - postgres
      - airflow_scheduler
    command: ["sh", "-c", "python scripts/api_call.py && tail -f /dev/null"]  # Keep container running

  # Jupyter for transformations
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter_notebook
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data       # Mount the data directory
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - postgres  # Jupyter depends on PostgreSQL now instead of Oracle
    env_file:
      - .env     # loading env_file to be used within jupyterLab for transformation  

volumes:
  postgres_data:  # Volume for PostgreSQL database data